### ISSUE TITLE
Concurrency problems

### ISSUE THREAD

**Issue by Sqasher** [TheXTremeZero/LK-Informatik---Softwarepraktikum#2]
At the moment, the graphics and the logic both implement a second thread to be independent of the main UI thread, which needs to be non blocking, so the system can still interact with the app. 
This will cause problems since the entities could be drawn while they are still updated or the UI thread could call onUp, onDown or onShoot and cause trouble for the logic thread.

The simplest solution would be to merge the logic and graphics threads into one and do some locking in the onUp, onDown and onShoot methods.

**Comment by Gameonlp** [comment]
look at the logic Thread and my temporary (not working) solution
